modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Lykrast/Voyage/issues"

[[mods]]
modId="voyage"
version="${version}"
displayName="Voyage"
displayURL="https://www.curseforge.com/minecraft/mc-mods/voyage"
credits="Traverse for the idea of a lightweight biome mod"
authors="Lykrast"
description='''
A lightweight biome mod that adds more biomes to your game without adding anything that isn't a biome, like blocks or items.
'''

[[dependencies.voyage]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.voyage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
