modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Lykrast/Voyage/issues"

[[mods]]
modId="voyage"
version="${version}"
displayName="Voyage"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://example.com/"
credits="Traverse for the idea of a lightweight biome mod"
authors="Lykrast"
description='''
A lightweight biome mod that adds more biomes to your game without adding anything that isn't a biome, like blocks or items.
'''

[[dependencies.voyage]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.voyage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
